export const randomName = () => {
  const names = [
    'Anonymous Panda',
    'Adorable Jancy',
    'Astronomical Phenomena',
    'Robust Kimberly',
    'Reuben Levya',
    'Dalton Lockett',
    'Elizabeth Tudor',
    'Bloddy Mary',
    'Gret Steppe',
    'Blake Biddy',
    'Beau Biffle',
    'Arla Albers',
    'Ashly Andrepont',
    'Dudley Dublin',
    'Temeka Tumlinson',
    'Lan Ledet',
    'Jena Jaquez',
    'Taunya Terhaar',
    'Rosia Rutland',
    'Benton Bulfer',
    'Derrick Dewar',
    'Eva Eisenmann',
    'Miyoko Maysonet',
    'Artie Amarante',
    'Cortez Clouser',
    'Stephenie Sheikh',
    'Jaunita Jefferis',
    'Nakesha Navarrette',
    'Charisse Chaves',
    'Brigid Briley',
    'Claretta Corr',
    'Cheyenne Contos',
    'Billy Baskin',
    'Mechelle Mcpeak',
    'Marlene Mortimer',
    'Santo Six',
    'Rowena Rosas',
    'Kristyn Karney',
    'Roxane Rebuck',
    'Bernardina Baros',
    'Nora Norville',
    'Susana Stambaugh',
    'Concetta Carballo',
    'Jimmie Janes',
    'Senaida Santibanez',
    'Kareem Knoblock',
    'Myung Marsh',
    'Reena Rumery',
    'Nancey Ness',
    'Lori Lamorte',
    'Myesha Montez',
    'Gena Gassett',
    'Steffanie Saez',
    'Dotty Donner',
    'Enola Erazo',
    'Keitha Kuster',
    'Freda Fifield',
    'Zola Zajicek',
    'Shona Saul',

  ]
  return names[Math.floor(Math.random() * names.length)];
}